/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package From_QLTV;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;

/**
 *
 * @author daovi
 */
public class Form_Dang_Nhap extends javax.swing.JFrame {
    String  driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=Account"; 
    String user = "sa";
    String password = "123456@Ab";
    Statement st;
    ResultSet rs;
    /**
     * Creates new form JFrameDemo
     */
    public Form_Dang_Nhap() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        titleText = new javax.swing.JLabel();
        userPass = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        passwordBox = new javax.swing.JPasswordField();
        btn__login = new javax.swing.JButton();
        checkRMB = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        userBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Form");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setForeground(new java.awt.Color(255, 255, 255));
        loginPanel.setFont(new java.awt.Font("Space Mono", 1, 11)); // NOI18N

        titleText.setFont(new java.awt.Font("Space Mono", 1, 18)); // NOI18N
        titleText.setForeground(new java.awt.Color(51, 153, 255));
        titleText.setText("ACCOUNT LOGIN");

        userPass.setFont(new java.awt.Font("Space Mono", 1, 14)); // NOI18N
        userPass.setForeground(new java.awt.Color(153, 153, 153));
        userPass.setText("PASSWORD");

        userName.setFont(new java.awt.Font("Space Mono", 1, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(153, 153, 153));
        userName.setText("USERNAME");

        passwordBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordBoxActionPerformed(evt);
            }
        });

        btn__login.setBackground(new java.awt.Color(51, 153, 255));
        btn__login.setFont(new java.awt.Font("Space Mono", 1, 12)); // NOI18N
        btn__login.setForeground(new java.awt.Color(255, 255, 255));
        btn__login.setText("LOG IN");
        btn__login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn__login.setBorderPainted(false);
        btn__login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn__loginActionPerformed(evt);
            }
        });

        checkRMB.setBackground(new java.awt.Color(255, 255, 255));
        checkRMB.setFont(new java.awt.Font("Space Mono", 0, 11)); // NOI18N
        checkRMB.setText("Show Password");
        checkRMB.setBorder(null);
        checkRMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRMBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Space Mono", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText(" Forgot Password?");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        userBox.setPreferredSize(new java.awt.Dimension(41, 18));

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn__login, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addComponent(userName)
                    .addComponent(userPass)
                    .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(checkRMB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addComponent(passwordBox)
                    .addComponent(userBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(checkRMB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btn__login, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn__loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn__loginActionPerformed
       try
        {
            Class.forName(driver);
            Connection con=DriverManager.getConnection(url, user, password);
            String sql = "SELECT * FROM ACCOUNT where UserName=? and Pass=? ";
            PreparedStatement ps=con.prepareStatement(sql);
           
            ps.setString(1,userBox.getText());
            ps.setString(2,passwordBox.getText());
            rs=ps.executeQuery();
           if(userBox.getText().equals("")||passwordBox.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Bạn chưa nhập Username và Password");
            }
           else if(rs.next()){//nếu có dữ liệu
           
             Quan_Ly_Sach_Thu_Vien showFrameFunction = new Quan_Ly_Sach_Thu_Vien();
             showFrameFunction.setVisible(true);
             this.dispose();
             JOptionPane.showMessageDialog(this, "Đăng nhập thành công"); 
            }
            else{
              JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không chính xác");     
            }
        }
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, e.getMessage());
        }
       
        
    }//GEN-LAST:event_btn__loginActionPerformed

    private void passwordBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordBoxActionPerformed

    private void checkRMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRMBActionPerformed
        // TODO add your handling code here:
        if(checkRMB.isSelected()) {
            passwordBox.setEchoChar((char)0);
        } else {
            passwordBox.setEchoChar('*');
        }
    }//GEN-LAST:event_checkRMBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Dang_Nhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Dang_Nhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn__login;
    private javax.swing.JRadioButton checkRMB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passwordBox;
    private javax.swing.JLabel titleText;
    private javax.swing.JTextField userBox;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userPass;
    // End of variables declaration//GEN-END:variables
}
